library(dplyr)
library(hflights)
filter(hflights, Distance >= 3000)
filter(hflights, UniqueCarrier %in% c("JetBlue", "Southwest", "Delta"))
filter(hflights, (TaxiOut + TaxiIn) > (AirTime))
filter(hflights, DepTime < 500 | ArrTime > 2200)
filter(hflights, DepDelay > 0 & ArrDelay < 0)
filter(hflights, DepDelay > 0 & Cancelled == 1)
c1 <- filter(hflights, Dest == "JFK")
c2 <- mutate(c1, Date = paste(Year, Month, DayofMonth, sep = "-"))
select(c2, Date, DepTime, ArrTime, TailNum)
filter(hflights, DayOfWeek %in% c('6', '7') & Distance > 1000 & (TaxiIn + TaxiOut < 15))
dtc <- filter(hflights, Cancelled == 1, !is.na(DepDelay))
arrange(dtc, DepDelay)
arrange(dtc, CancellationCode)
arrange(dtc, UniqueCarrier, DepDelay)
arrange(hflights, UniqueCarrier, desc(DepDelay))
arrange(hflights, (DepDelay + ArrDelay))
